version: '3.1'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - var/lib/postgresql/data
    env_file:
      - database.env
